[package] 
name = "hcms-29xx"
version = "0.1.0"
edition = "2021"
authors = ["Nick Brown <nick@altonimb.us>"]
categories = ["embedded", "no-std"]
description = "Driver for HCMS-29XX and HCMS-39XX display ICs"
license = "MIT"
repository = "https://github.com/nonik0/hcms-29xx"
readme = "README.md"

[dependencies]
embedded-hal = "1.0.0"
avr-progmem = "0.4.0" # TODO: use as feature

# The latest releases of `proc-macro2` do not support the rust toolchain that
# we use.  Thus, we must fix this dependency to an older version where our
# toolchain is still supported.  See https://github.com/Rahix/avr-hal/issues/537
[build-dependencies.proc-macro2]
version = "=1.0.79"

#[[example]]
#name = "arduino-uno"

#[dependencies.arduino-hal]
#path = "../../arduino-hal/"
#features = ["arduino-uno"]